### PR TITLE
Fixes and testing extreme templates

### LINKED ISSUE #959: tables with reference columns RSPT01

### PR DESCRIPTION
**Pull request by Melkiades**
Fixes #959 #964 #963 #960 #961

### CODE REVIEW

File: R/tt_as_df.R [hunk 1]
```diff
@@ -238,11 +244,13 @@ as_result_df <- function(tt, spec = NULL,
         stat_name <- setNames(cell_stat_names[, col_i - min(only_col_indexes) + 1, drop = TRUE], NULL)
         stat <- setNames(ret_tmp[!col_label_rows, col_i, drop = TRUE], NULL)
         necessary_stat_lengths <- sapply(stat, length)
+        stat[sapply(stat, is.null)] <- NA
 
         # Truncating or adding NA if stat names has more or less elements than stats
         stat_name <- lapply(seq_along(stat_name), function(sn_i) {
           stat_name[[sn_i]][seq_len(necessary_stat_lengths[sn_i])]
         })
+        stat_name[sapply(stat_name, function(x) length(x) == 0)] <- NA
```
Comment (edelarua) [inline R/tt_as_df.R:253]: Would this work? It's a bit cleaner :)

```suggestion
        stat_name[!nzchar(stat_name)] <- NA
```

File: tests/testthat/test-result_data_frame.R [hunk 2]
```diff
@@ -239,6 +239,16 @@ test_that("as_result_df works fine with empty tables and no character(0) is allo
   )
 })
 
+test_that("as_result_df works with only analyze tables (odd num of path elements)", {
```
Comment (edelarua) [inline tests/testthat/test-result_data_frame.R:242]:
```suggestion
test_that("as_result_df works with analyze-only tables (odd num of path elements)", {
```

**Review by edelarua — APPROVED** [review]
Thanks Davide! A few suggestions but otherwise all great!! :)
