### PR TITLE
Fix `as_html` newlines and add parameters to `export_as_tsv`

### LINKED ISSUE #898: Relying on html resolution of newline characters by adding `expand_newline = FALSE` as parameter to `as_html`
The scope is to have cells with `\n` behaving as a single cell and not more than one. Hence, it will not be {formatters} expanding newlines, but the HTML output will keep it until printing. The following example has also indentation and col/row names newlines:
``` r
library(rtables)
#> Loading required package: formatters
#> 
#> Attaching package: 'formatters'
#> The following object is masked from 'package:base':
#> 
#>     %||%
#> Loading required package: magrittr
#> 
#> Attaching package: 'rtables'
#> The following object is masked from 'package:utils':
#> 
#>     str
```

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
```

``` r

iris_mod <- iris %>%
  mutate(Species2 = as.factor(paste0("General", "\n ", as.character(Species)))) %>% 
  mutate(Species = as.factor(sample(paste0("Petal", "\n ", as.character(Species)))))
  

lyt <- basic_table() %>%
  split_cols_by("Species") %>%
  split_rows_by("Species2") %>% 
  analyze("Sepal.Length", afun = function(x) {
    list(
      "mean \n (sd)" = rcell(c(mean(x), sd(x)), format = "xx.xx (xx.xx)"),
      "range" = diff(range(x))
    )
  })

tbl <- build_table(lyt, iris_mod)
tbl
#>                  Petal         Petal         Petal   
#>                  setosa      versicolor    virginica 
#> —————————————————————————————————————————————————————
#> General                                              
#>  setosa                                              
#>   mean        5.07 (0.41)   5.06 (0.35)   4.90 (0.28)
#>    (sd)                                              
#>   range           1.3           1.4           1.2    
#> General                                              
#>  versicolor                                          
#>   mean        5.83 (0.46)   6.16 (0.53)   5.85 (0.56)
#>    (sd)                                              
#>   range           1.8           1.6           1.7    
#> General                                              
#>  virginica                                           
#>   mean        6.25 (0.23)   6.46 (0.77)   6.88 (0.56)
#>    (sd)                                              
#>   range           0.7            3            1.9
```

``` r

library(tern)
#> Registered S3 method overwritten by 'tern':
#>   method   from 
#>   tidy.glm broom
```

``` r
library(shiny)

ui <- fluidPage(
  uiOutput("table")
)
server <- function(input, output, session) {
  output$table <- renderUI({
    as_html(tbl)
  })
}
shinyApp(ui, server)
#> 
#> Listening on http://127.0.0.1:8160
```

<sup>Created on 2024-07-09 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by Melkiades**
Fixes #898 #289

### CODE REVIEW

File: tests/testthat/test-as_html.R [hunk 1]
```diff
@@ -0,0 +1,139 @@
...
+    as.character(res$children[[1]][[2]]$children[[7]]$children[[1]][[1]]),
+    '<td style="text-align: left; padding-left: 3ch;"></td>'
+  )
+  expect_equal(
+    as.character(res$children[[1]][[2]]$children[[7]]$children[[1]][[2]]),
+    '<td style="text-align: center;">  ^  </td>'
+  )
+})
+
+test_that("as_html expands or not newlines depending on expand_newlines", {
```
Comment (Melkiades) [inline tests/testthat/test-as_html.R:116]: only added this test. the rest is coming from moving out these test from the large exporter test file

**Review by ayogasekaram — APPROVED** [review]
lgtm @Melkiades! Thank you for the fix :)
