### PR TITLE
bug fixes and init pagination

### LINKED ISSUE #929: docx - Issues with colcounts in different lines and interline for first cell values

### PR DESCRIPTION
**Pull request by Melkiades**
fixes #929 still some things to brew

### CODE REVIEW

File: tests/testthat/test-exporters.R [hunk 1]
```diff
@@ -260,9 +260,6 @@ test_that("Can create flextable object that works with different styles", {
   ft <- tt_to_flextable(tbl, total_width = 20)
   expect_equal(sum(unlist(nrow(ft))), 20)
 
-  ft2 <- tt_to_flextable(tbl, paginate = TRUE, lpp = 20, verbose = TRUE)
-  expect_equal(length(ft2), 2)
```
Comment (Melkiades) [inline tests/testthat/test-exporters.R:264]: pagination to come

File: tests/testthat/test-exporters.R [hunk 2]
```diff
@@ -312,7 +308,7 @@ test_that("Can create flextable object that works with different styles", {
 
   expect_equal(flextable::nrow_part(topleft_t2, part = "header"), 2L)
   expect_equal(flextable::nrow_part(topleft_t1a, part = "header"), 1L)
-  expect_equal(flextable::nrow_part(topleft_t1b, part = "header"), 2L)
+  expect_equal(flextable::nrow_part(topleft_t1b, part = "header"), 1L)
```
Comment (Melkiades) [inline tests/testthat/test-exporters.R:311]: this is the right answer because it still stays in the same cell

File: NEWS.md [hunk 3]
```diff
@@ -4,17 +4,26 @@
  * Removed `tt` input from `theme_docx_default()` and added internal handling for row classes and number of columns.
  * Reworked padding and spacing in default theme `theme_docx_default()`.
  * Added top left information handling (now bold and bottom aligned).
+ * Now users can add more than one theme to `tt_to_flextable()`, and/or extend themes.
+ * Added default theme for `.html` outputs.
+ * Added parameter `bold_titles` to `tt_to_flextable()` to bold titles.
 
 ### Bug Fixes
  * Fixed `"\n"` newline issues in `as_html` by relying onto output devices for newline handling. Added `expand_newlines = FALSE` default to allow previous behavior.
  * `keep_split_levels` throws now an error if the user requests to keep levels that are not present in data.
```
Comment (shajoezhu) [inline NEWS.md:13]:
```suggestion
 * `keep_split_levels()` throws now an error if the user requests to keep levels that are not present in data.
```

File: NEWS.md [hunk 4]
```diff
@@ -4,17 +4,26 @@
...
+ * Fixed issue with removal of horizontal lines in `tt_as_flextable` header when title was added.
```
Comment (shajoezhu) [inline NEWS.md:14]:
```suggestion
 * Fixed issue with removal of horizontal lines in `tt_as_flextable()` header when title was added.
```

File: tests/testthat/test-exporters.R [hunk 5]
```diff
@@ -361,3 +357,67 @@ test_that("export_as_doc works thanks to tt_to_flextable", {
...
+    analyze("AGE")
+
+  tbl <- build_table(lyt, ex_adsl)
+
+  main_title(tbl) <- "Main title"
+  subtitles(tbl) <- c("Some Many", "Subtitles")
+  main_footer(tbl) <- c("Some Footer", "Mehr")
+  prov_footer(tbl) <- "Some prov Footer"
+
+  expect_silent(out <- tt_to_flextable(tbl, paginate = TRUE, lpp = 100))
```
Comment (shajoezhu) [inline tests/testthat/test-exporters.R:422]: can we snapshot this?

File: R/tt_export.R [hunk 6]
```diff
@@ -631,7 +631,12 @@ export_as_docx <- function(tt,
     if (isFALSE(titles_as_header) || isTRUE(footers_as_text)) {
       # Ugly but I could not find a getter for font.size
       font_sz <- flex_tbl$header$styles$text$font.size$data[1, 1]
```
Comment (shajoezhu) [inline R/tt_export.R:633]: change font_sz to font_sz_body, keep aligned with font_sz_footer

File: R/tt_export.R [hunk 7]
```diff
@@ -631,7 +631,12 @@ export_as_docx <- function(tt,
...
-      font_sz_footer <- flex_tbl$header$styles$text$font.size$data[1, 1] - 1
+      footer_sizes <- flex_tbl$footer$styles$text$font.size$data
```
Comment (shajoezhu) [inline R/tt_export.R:634]: footer_sizes and footer_sizes are bit confusing with the naming.

File: R/tt_export.R (hunk 6 above)
Comment (shajoezhu) [reply R/tt_export.R:633]: or consider, adding officer_font_sz_footer, as it is used in officer

File: tests/testthat/test-exporters.R (hunk 5 above)
Comment (shajoezhu) [reply tests/testthat/test-exporters.R:422]: The reason I ask is that I was thinking to write a s3 function of as_flextable.rtables, then we can fully utilize flextable functions such as information_data_chunk, and etc, instead of us writing functions. perhaps next version. perhaps in the next version of this function, we could do something like this.

Comment (Melkiades) [reply tests/testthat/test-exporters.R:422]: I see extending as_flextable... It may makes sense but we need probably to import it at that time? 
I can snapshot that yes, but only the data, the style is a bit more complex

Comment (Melkiades) [reply tests/testthat/test-exporters.R]: I will work on the pagination precisely in the next PR

**Comment by Melkiades** [comment]
@shajoezhu I was getting a bit lost between functions, so I split the flextable and data.frame transformers into other files. No other changes since last review (beside the comments' fixes). I think we can merge it and then I will continue with pagination fixes

**Review by shajoezhu — APPROVED** [review]
lgtm! thanks @Melkiades
