### PR TITLE
Fix: more edge cases for `stat_string`

### LINKED ISSUE #1001: Bug in `as_result_df` stat_string output not matching stat output when empties are present
- [x] allow to turn it off if rows do not match
- [x] fix the bug

### PR DESCRIPTION
**Pull request by Melkiades**
Fixes #1001 and https://github.com/insightsengineering/rtables/issues/1004

### CODE REVIEW

**Comment by Melkiades** [comment]
@ayogasekaram this PR!

File: tests/testthat/test-result_data_frame.R [hunk 1]
```diff
@@ -583,10 +585,14 @@ test_that("make_ard works when printed format differs from cell values", {
 
   expect_warning(
     out <- as_result_df(test_out, make_ard = TRUE, verbose = TRUE),
-    "Found 9 cell"
+    paste0(
+      "Found 1 cell values that differ from printed values. ",
+      "This is possibly related to conditional formatting. ",
+      "\\\nThe following row names were modified: Mean \\(SD\\), Mean \\(SD\\)\\\n"
```
Comment (Melkiades) [inline tests/testthat/test-result_data_frame.R:591]: one of the issues concerned this specific output. Hence, I wrote it all. It was giving all the lines, which was not exact (lengths_keep_nuls solves this)

**Comment by ayogasekaram** [comment]
> @ayogasekaram this PR!

Thank you for making these changes Davide! I'm still getting errors when trying to run as_results_df on LBT01 and TTET01 after installing this branch.

LBT01:
```
library(chevron)

# Create a table using the chevron package 
tlg_lbt01 <- chevron::lbt01_main(syn_data, lbl_overall = "Overall ARM")
rtables_results <- rtables::as_result_df(tlg_lbt01, make_ard = TRUE, expand_colnames = TRUE)
```
image


TTET01:
```
library(chevron)

# Create a table using the chevron package 
proc_data <- dunlin::log_filter(syn_data, PARAMCD == "PFS", "adtte")
tlg_ttet01 <- chevron::run(ttet01, proc_data)

results <- rtables::as_result_df(tlg_ttet01, make_ard = TRUE, expand_colnames = TRUE)
```
image

**Comment by Melkiades** [comment]
> # Create a table using the chevron package 
> proc_data <- dunlin::log_filter(syn_data, PARAMCD == "PFS", "adtte")
> tlg_ttet01 <- chevron::run(ttet01, proc_data)
> 
> results <- rtables::as_result_df(tlg_ttet01, make_ard = TRUE, expand_colnames = TRUE)

They both work for me. I do not think you pulled the right branch ;)

**Comment by shajoezhu** [comment]
lets check downstream https://github.com/insightsengineering/rtables/actions/runs/13827633328

File: R/tree_accessors.R [hunk 2]
```diff
@@ -3646,7 +3646,7 @@ setMethod(
       return(NULL)
     }
 
-    return(all_col_fnotes)
+    all_col_fnotes
```
Comment (shajoezhu) [inline R/tree_accessors.R:3649]: if is.null(unlist(all_col_fnotes))

isn't all_col_fnotes NULL? I was wondering if you could add a test case to check the condition at the line 3645, if this is necessary? thanks

File: R/tt_pos_and_access.R [hunk 3]
```diff
@@ -306,10 +306,11 @@ setMethod(
   while (length(cur_path > 0)) {
     kids <- tree_children(cur_tbl)
     curname <- cur_path[1]
+    kids_names <- sapply(kids, obj_name)
```
Comment (shajoezhu) [inline R/tt_pos_and_access.R:309]: from the line 309 to the line 333, this is a complex scenario, thanks for considering all cases, @Melkiades , can you please add explicit test case for each scenario path

File: R/tt_as_df.R [hunk 4]
```diff
@@ -116,17 +118,19 @@ as_result_df <- function(tt, spec = NULL,
...
-        colnames(selected_rows_to_print) <- c("row_number", "row_name", colnames(cellvals_init))
-        warning_msg <- if (verbose) {
+        warning_msg <- if (verbose) { # beware that \n will break this (use make_row_df(tt)$self_extent for fix)
+          selected_rows_to_print <- mf_strings(mf_tt)[-seq_len(mf_nlheader(mf_tt)), , drop = FALSE]
+          selected_rows_to_print <- selected_rows_to_print[!make_row_df(tt)$node_class == "LabelRow", , drop = FALSE]
+          selected_rows_to_print <- cbind(
+            which(apply(dmc, 1, any, simplify = TRUE)),
+            as.data.frame(selected_rows_to_print[apply(dmc, 1, any), , drop = FALSE])
+          )
+          colnames(selected_rows_to_print) <- c("row_number", "row_name", colnames(cellvals_init))
```
Comment (shajoezhu) [inline R/tt_as_df.R:133]: i have a feeling we might have to come back with warning messages, it is ok for now.

File: R/tree_accessors.R (hunk 2 above)
Comment (Melkiades) [reply R/tree_accessors.R:3649]: This was only a lintr fix. I can check this case

Comment (shajoezhu) [reply R/tree_accessors.R:3649]: yes, i think this was the new styler thing, i was referring a couple of lines before

File: R/tt_pos_and_access.R (hunk 3 above)
Comment (Melkiades) [reply R/tt_pos_and_access.R:309]: Yes! I would move it to another issue as this needs a bit of time to understand when this can be used and extend behavior. For the moment, it is only a safe-net and I think we need this PR in for as_result_df first

File: R/tree_accessors.R (hunk 2 above)
Comment (Melkiades) [reply R/tree_accessors.R:3649]: I think the default for footnotes is `NULL`, so it looks correct to me. I would not try to make a test out of this function as I do not have a deep understanding of the footnotes mechanism

File: R/tt_pos_and_access.R (hunk 3 above)
Comment (Melkiades) [reply R/tt_pos_and_access.R:309]: Opened a new issue regarding this

**Review by shajoezhu — APPROVED** [review]
lgtm! thanks @Melkiades
