### PR TITLE
`hsep` propagation fix

### LINKED ISSUE #778: Consider passing `hsep` into exporters
```r
lyt <- basic_table() %>%
  split_cols_by("Species") %>%
  analyze("Sepal.Length", afun = function(x) {
    list(
      "mean (sd)" = rcell(c(mean(x), sd(x)), format = "xx.xx (xx.xx)"),
      "range" = diff(range(x))
    )
  })


tbl <- build_table(lyt, iris, hsep = "~")
export_as_txt(tbl) %>% cat() # does not have ~ if not specified again
```

### PR DESCRIPTION
**Pull request by Melkiades**
to merge after https://github.com/insightsengineering/formatters/pull/228

Fixes #778

### CODE REVIEW

File: tests/testthat/test-printing.R [hunk 1]
```diff
@@ -739,3 +739,20 @@ test_that("Separators and wrapping work together with getter and setters", {
...
+        "mean (sd)" = rcell(c(mean(x), sd(x)), format = "xx.xx (xx.xx)"),
+        "range" = diff(range(x))
+      )
+    })
+  
+  tbl <- build_table(lyt, iris, hsep = "~")
+  tostring_tbl <- strsplit(toString(tbl), "\n")[[1]]
+  export_txt_tbl <- strsplit(export_as_txt(tbl), "\n")[[1]]
+  expect_identical(tostring_tbl, export_txt_tbl)
+})
```
Comment (edelarua) [inline tests/testthat/test-printing.R:758]: Add end of file empty line

**Review by edelarua — APPROVED** [review]
Lgtm!! Just one minor suggestion from me. Everything is working great! :)
